# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df99c1a78f40baeef56e89246cd81034"
name = "song-1"
handle = "song-3"
application_url = "https://2f0b0b5391c9.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://2f0b0b5391c9.ngrok-free.app/auth/callback", "https://2f0b0b5391c9.ngrok-free.app/auth/shopify/callback", "https://2f0b0b5391c9.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
